on:
  push:
    branches:
      - master
name: Deploy to GitHub Pages
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          npm ci
      - name: Trigger deployment command
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run deploy
